### ISSUE TITLE
请问显示微信id该功能是如何使用的？

### ISSUE THREAD

**Issue by jk1420** [veryyoung/WechatLuckyMoney#103]

**Comment by veryyoung** [comment]
用来设置黑名单的，请看 readme

**Comment by jk1420** [comment]
@veryyoung  我进入群信息页和用户信息页都无法获取到微信id，请问这个问题有什么思路可以解决

**Comment by veryyoung** [comment]
@jk1420 打开“显示微信ID”就行了

**Comment by jk1420** [comment]
@veryyoung 我的微信版本是6.5.7，打开显示微信id后进入用户信息页面或者群信息页面都没有提示已复制用户微信id的提示，同时剪贴板也没有微信id的内容
