### ISSUE TITLE
查询红包明细请求,call和hook哪个函数呢

### ISSUE THREAD

**Issue by lelilin** [veryyoung/WechatLuckyMoney#105]
callMethod(requestCaller, "a", luckyMoneyRequest, getDelayTime());  --------为抢红包函数请求.
 若查询红包明细请求,call和hook哪个函数呢?
望提供点意见？

**Comment by veryyoung** [comment]
这个需要自己分析，请勿伸手，谢谢。

**Comment by lelilin** [comment]
也并非伸手,是来请教的,看能不能给个思路.
callMethod(requestCaller, "a", luckyMoneyRequest, getDelayTime()); 放在线程中执行多次.
hook  com.tencent.mm.plugin.luckymoney.c.ab,获取红包明细.但都只能显示第一次的明细 ？何解？
