### ISSUE TITLE
麻烦吧 apk 文件更新下

### ISSUE THREAD

**Issue by uojo** [veryyoung/WechatLuckyMoney#107]
app-release  是不是没有提交，不是最新的，不支持 6.5.7

**Comment by uojo** [comment]
大神，麻烦每次更新的时候 把 apk 一起

**Comment by SwordAbuse** [comment]
能加个扫雷功能吗

**Comment by lovefrr** [comment]
能加个约炮功能吗？

**Comment by veryyoung** [comment]
@lovefrr 请参考 http://www.coolapk.com/apk/com.p1.mobile.putong
