### ISSUE TITLE
1.24和1.25版插件使用情况反馈和建议

### ISSUE THREAD

**Issue by woyiye** [veryyoung/WechatLuckyMoney#108]
大神您好！首先要对您开发的红包插件表示敬意！

使用反馈：
        一、插件如果开启延时抢包功能的话，锁屏状态下就不会自动抢或者说要隔很长时间（超出设置的时间范围）才抢包，关闭延时立即抢则不会。
        二、如果关闭延时立即抢或者设置检测到红包关键字不抢的话，有时会出现被微信后台检测出用使用红包辅助的警告。

完善建议：
        我认为，随机延时抢包功能、过滤红包关键字功能是必备的，可否再增加抢包后自动随机回复自设定的几个答谢语的功能？这三个功能备齐就完美了！前提是都在锁屏状态下功能正常。
        谢谢！

**Comment by veryyoung** [comment]
@woyiye 锁屏后能不能抢取决于微信还在不在后台运行，这超出本软件的范畴。

自动回复是很简单实现的事情，建议你自己在现在的基础上扩展，只要遵循 GPL 协议就行。

**Comment by ydh7611** [comment]
@veryyoung 杨老师，您好，您说的自动回复很简单，可以给个实现思路吗？比如，我用xp把微信启动了，怎么根据好友的ID或用户名实例化一个聊天实例并向此好友发消息呢，谢谢。
希望老师能在百忙之中回复一下，授人以鱼不如授人以渔，也正是GPL协议的精华吧，老师辛苦了！

**Comment by veryyoung** [comment]
@ydh7611 GPL 协议并不是给伸手党来提供帮助的。
