### ISSUE TITLE
关于6.5.8微信

### ISSUE THREAD

**Issue by 873578156** [veryyoung/WechatLuckyMoney#113]
我发现在我更新5月31号的play版微信6.5.8以后，红包失效了。

**Comment by walaoaaa1234** [comment]
#110

**Comment by godboy0913** [comment]
我的升级的并不是play版，但也用不了

**Comment by godboy0913** [comment]
我之前是微信6.5.6，搭配1.2.5的是正常的
看到有新版本1.2.6，并且适配6.5.8，就先将1.2.5里所有功能都关闭，再在xposed里将1.2.5停用，重启手机，升级微信到6.5.8，升级插件到1.2.6，重启，到xposed里启用插件，重启，进插件开启抢红包的各种功能？我以前升级也碰到过插件失效的问题，后来就根据这个流程操作，都可以正常使用了，但这次不行
发现快速拆包跟显示微信ID是正常的，唯独不会自动抢红包，延时关闭也不抢
我就又按照上面的来，折腾了几次，依旧
然后停用插件，重启，卸载，重启，安装重启，启用，重启，还是一样不会抢，不知道问题出在哪里了
有人帮帮我吗？或者交流下，你们是怎么操作升级的？或者指点下，我哪做的不对？

**Comment by godboy0913** [comment]
下午将微信版本重新安装成6.5.6的，红包插件还是用1.2.6的版本，抢红包功能正常了
这说明1.2.6不支持6.5.8吗

**Comment by Milittle** [comment]
![_20170603131115](https://cloud.githubusercontent.com/assets/9550695/26750832/320940f4-485e-11e7-818f-89372abe1945.jpg)
有谁遇到了这个问题~

**Comment by godboy0913** [comment]
没有碰到过这样的问题

**Comment by nqs120** [comment]
什么时候出微信6.5.8版本的啊
