### ISSUE TITLE
关于黑名单

### ISSUE THREAD

**Issue by abackey** [veryyoung/WechatLuckyMoney#114]
说实话，这个功能🆚思路都8特别厉害。不过使用中，还是有点小问题。设置进黑名单里的群，插件是不会自动再抢了。但是黑名单里的个人用户，插件还是会自动去抢他发的红包（这个好像是随机的，也不是个个都拦不住）。。请问大神，可否在下个版本里修复一下，非常感谢

**Comment by veryyoung** [comment]
@abackey 禁止个人这段逻辑，经过测试，是没问题的。

**Comment by abackey** [comment]
我实际遇到的情况是，对方发了3个红包，第一个自动抢了，后2个没抢。
这种情况出现多次了。。

**Comment by veryyoung** [comment]
@abackey 如果是个人用户，只能禁止他给你私聊发的红包，并不能禁止他在群里发的。

**Comment by abackey** [comment]
原来是这样啊。。。那有没有办法禁止抢群里某个人的呢？？可否考虑在包含关键字不抢的选项里拓展这个功能呢？？
不论如何，感谢大神的耐心讲解，你的插件很赞

**Comment by veryyoung** [comment]
@abackey 收到的 message 包含群和个人的 id，实现起来比较容易，建议自己搞~

**Comment by abackey** [comment]
不会搞啊。。。没那个技术😭
你的插件是真的做的好。。
不论怎样都要感谢你啊！！！
谢谢😘😚😗😙
