### ISSUE TITLE
 path问题

### ISSUE THREAD

**Issue by WuLex** [veryyoung/WechatLuckyMoney#116]
`
E/System: stat file error, path is /data/app/siso.wechatluckymoney-1/lib/arm64, exception is android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
`
我自己新建了一个项目，然后把你的对应的拷贝，结果一直出现这个问题...

**Comment by veryyoung** [comment]
@WuLex 原因我不清楚啦，你可以先尝试编译下我的项目。
