### ISSUE TITLE
Megisk support (android N 7.1)

### ISSUE THREAD

**Issue by ahdkli** [veryyoung/WechatLuckyMoney#118]
Hello I don't speak chinese so I used translation software, Xposed now doesn't work on android 7.1
But we can use the Megisk as a replacement for Xposed.  Is there any chance you can make the app again and put it for Megisk ? 

你好，我不会说中文，所以我用翻译软件，Xposed现在不工作在android 7.1
但是我们可以使用Megisk作为Xposed的替代品。有没有机会再次使用该应用程序并将其用于Megisk？

**Comment by walaoaaa1234** [comment]
@ahdkli as the owner mentioned in issue #93 , due to the less module and user in magisk, it's not worth.
