### ISSUE TITLE
怎么需要关闭那个ui？？

### ISSUE THREAD

**Issue by xfunforx** [veryyoung/WechatLuckyMoney#12]
好像用的是很旧的东西，最开始的方法就是走的ui层，所以需要关闭抢到后的那个窗口。

后面的就不需要走ui了，是不需要关闭窗口的。 somecode那个地方的代码就是完全不需要关闭的ui。

**Comment by veryyoung** [comment]
微信这个版本不需要操作 UI 啦！！

**Comment by veryyoung** [comment]
@xfunforx 微信的一直不需要操作 UI 啊。我只是做了个手动快捷拆红包的功能。

**Comment by 1977helj** [comment]
@veryyoung 大哥你的代码的确用的太老了，我也看了。建议使用xfunforx发布的最新代码somecode

**Comment by veryyoung** [comment]
@1977helj 代码太旧是啥意思？我是基于最新微信来开发的啊。

**Comment by 1977helj** [comment]
@veryyoung 现在版本我编译使用了，群多红包多的话100%失效，要么抢一会就不抢了，要么抢几个包就提示异常操作，总之毛病很多（超过100群实测）而用xfunforx的代码就没问题。之前wuxianlin的红包插件也是用xfunforx的代码改造的，红包没有漏的。他们的代码里拆红包那完全不需要ui，所以基本不会提示抢红包异常操作，微信把你号封了，都可以继续抢，特别霸道。

**Comment by xfunforx** [comment]
@veryyoung 代码旧不是指适配的微信版本旧，是指里面的处理逻辑使用了 以前的抢红包工具的逻辑。

**Comment by xfunforx** [comment]
@veryyoung 如果你说是不需要走ui的话，那就是没错了，可能是我眼花看错了。没留意到你说的  “我只是做了个手动快捷拆红包的功能。”
