### ISSUE TITLE
如何更快捷的分析wx的apk

### ISSUE THREAD

**Issue by Windy19991999gmailcom** [veryyoung/WechatLuckyMoney#122]
我想知道，如何更快捷的分析wx的apk，因为里面大部分都是已经混淆过得代码，而且我在xposed中已经对每个方法做了aop，但是貌似这样太多东西要看，经常有一些重复调用的

**Comment by AnthonyZhang12** [comment]
求分享

**Comment by lytasky** [comment]
求分享 ，+1问  系统消息(比如好友申请、新人入群之类)该hook什么方法呢？
