### ISSUE TITLE
插件不生效 play版本

### ISSUE THREAD

**Issue by 873578156** [veryyoung/WechatLuckyMoney#125]
我发现play版本的插件都不生效，从6.5.8开始，希望改善

**Comment by veryyoung** [comment]
@873578156 压根没适配过 play 版哦，只适配了官方版

**Comment by vipzrx** [comment]
@veryyoung
1 官方版本，指的是从下载的吗？
https://weixin.qq.com/

2 请问你只适配官方的微信，可以支持pay版本微信的适配吗？

**Comment by superewe** [comment]
@veryyoung
在适配官方微信的过程中，能感觉出官方的和pay的微信有什么差别吗？

**Comment by veryyoung** [comment]
@vipzrx
问题1：是。
问题2：不太有空支持啦。

我没适配过 play 版，所以没法回答啦。 @superewe

**Comment by xuzc** [comment]
多版本适配很辛苦的 同感😭

**Comment by superewe** [comment]
@xuzc 你也在做微信插件开发的相关工作吗？需要适配多个微信吗？
@veryyoung 微信在自己的网站上或者通过热更新来升级微信，对于微信是最方便的。毕竟pay在国内使用环境恶略。

不清楚你开发这个插件的初衷是什么？ 如果是为了有个比较好用的微信+一些插件实现的定制的功能，可否选择一个好用的微信旧版本做长期支持？
pay版本是个不错的选择

**Comment by veryyoung** [comment]
@superewe 我开发这个的初衷是自己想玩，我只会用官方版的微信，所以其他版本不想适配啦。

有其他版本的人，自己适配下就 OK 啦，反正代码 open source。

**Comment by Naolador** [comment]
楼主搞个简单的教程教我们怎么适配play或别的版本嘛~毕竟大部分人不是dev，如果要从0开始学还是很迷茫的。我不清楚官方版和play版究竟有何区别（play上不也是官方推上去的吗），但感觉不会很难。

**Comment by 873578156** [comment]
@veryyoung 好的，了解了，因为我用的Nexus，所以基本都是play版本。我有时间自己适配下吧。
