### ISSUE TITLE
从微信6.58更新到6.5.10，不会自动领取红包

### ISSUE THREAD

**Issue by diaosi58** [veryyoung/WechatLuckyMoney#126]
Xposed 框架是86
微信版本6.58 能自动领取，升级到了微信6.5.10。不能自动领取，插件无效。

测试手机：
乐视S3  。EUI5.9  。  安卓系统：6.0

**Comment by blxc321** [comment]
一样.怎么解决？？

**Comment by walaoaaa1234** [comment]
请问是play版本还是，微信官方版本？

**Comment by diaosi58** [comment]
微信是官方版的，  Google Play 服务，是从 Google 市场里面更新到了最新版本的。

**Comment by veryyoung** [comment]
@diaosi58 不支持 play 版微信
