### ISSUE TITLE
寻求大佬帮助

### ISSUE THREAD

**Issue by s-outmen** [veryyoung/WechatLuckyMoney#128]
微信6.5.10获取红包领取详情，该hook哪个class的哪个方法，忘大佬指导一下，感激不尽。

**Comment by veryyoung** [comment]
@s-outmen 从 activity 入手

**Comment by s-outmen** [comment]
谢谢大佬回复，能详细说说吗？或者能留个其他联系方式吗？如果可以的话希望能订制这个功能。

**Comment by veryyoung** [comment]
@s-outmen 联系方式我的 github 主页有
