### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by wanwfy** [veryyoung/WechatLuckyMoney#13]
我装了个平行空间以后发现微信红包插件会导致官方微信和双开的微信闪退。把平行删除再重装微信也不行。红包插件禁用了就正常了。手机系统是flyme5.6

**Comment by veryyoung** [comment]
闪退不知道是不是我的锅。

解决方法。

`/data/data/com.tencent.mm/tinker里面的东西删掉，然后权限全0,完美解决闪退`

**Comment by tkisme** [comment]
$ adb shell
$ su
# rm -rf /data/app/com.tencent.mm/tinker/*
# chmod 000 /data/app/com.tencent.mm/tinker/

**Comment by veryyoung** [comment]
@tkisme 是哒。我在考虑下个版本把这段加到代码里面去。

**Comment by 514186** [comment]
参照此方法，MIUI8原始微信问题解决，但分身微信还是会卡死

**Comment by veryyoung** [comment]
@514186 分身之后 package 不同了。你需要找到对应的 package。

**Comment by 514186** [comment]
搞定，谢谢

**Comment by bangbangbao** [comment]
双开的微信找不到thinker在哪儿 也就无法打开了 该怎么解决

**Comment by veryyoung** [comment]
@bangbangbao   双开一样有对应类似 ```/data/data``` 的地方

**Comment by bangbangbao** [comment]
找不到这个具体的文件在哪儿😊 有没有具体一点的呢 不然双开就弄不了了

**Comment by veryyoung** [comment]
@bangbangbao 我不知道在哪，我不知道你用的什么双开应用。

你的问题和本插件无关。

**Comment by aviraxp** [comment]
@bangbangbao 全盘搜索

**Comment by vipzrx** [comment]
你的是什么版本？用低版本的微信
6.3.23这个闪退问题比较严重
使用 mt文件管理器，查看这个文件，没有的话，新建tinker文件夹，权限全0

**Comment by bangbangbao** [comment]
是MIUI8的自带双开软件

**Comment by bangbangbao** [comment]
希望有人能加下扣扣号923179466方便交流

**Comment by bangbangbao** [comment]
514186 你的是怎么解决的呢

**Comment by 14331195** [comment]
很容易被检测到怎么解决？（已经被检测到两次了）

**Comment by wangzhenjiang** [comment]
完美解决。。。。厉害。。。

**Comment by NoBodyKnowsTheTroubleIHaveSeen** [comment]
请问你知道微信这是怎么检测的吗

**Comment by xhsJ88** [comment]
安卓无法自动抢

**Comment by tkisme** [comment]
@veryyoung 
要不写在readme里面吧，😓

**Comment by beiguo** [comment]
luckymoney 6.3.32 不能用。。没有反应。 但是随即游戏可以用。

**Comment by tanter** [comment]
晕啊 抵制盗版 我们怎么办

**Comment by HKGmail** [comment]
安卓7.0可用吗?

**Comment by veryyoung** [comment]
@HKGmail 基于 xposed 的，Android 7.0 应该还没有 xposed 框架。

**Comment by 253145061** [comment]
我的微信为什么不管用

**Comment by nqs120** [comment]
闪退不知道是不是我的锅。

解决方法。

/data/data/com.tencent.mm/tinker里面的东西删掉，然后权限全0,完美解决闪退
能进入微信了可是不能自动抢红包，怎么解决？

**Comment by cyg14202190** [comment]
按照前边的方法删除了rm -rf /data/app/com.tencent.mm/tinker/*，然后建立文件夹，给权限，微信还是不能用啊，miui8系统，微信6.5.8，模块1.2.6

**Comment by daleiyinsi** [comment]
我的装上完全没反应,收到红包不闪退也不抢红包,就是完全没反应

**Comment by chenhaiAndroid** [comment]
微信 6.5.8不能用啊

**Comment by TangMonk** [comment]
最新版微信闪退啊

**Comment by fymser** [comment]
能发一个视频教程不

**Comment by 8177616** [comment]
/data/data/com.tencent.mm/tinker里面的东西删掉，然后权限全0,完美解决闪退
但是不抢包了 是不是不小心删掉了什么重要代码。

**Comment by chenhaiAndroid** [comment]
楼主是不是没有自己测试过就发上来了

**Comment by veryyoung** [comment]
@chenhaiAndroid 你是不是没测过就来提问了？
