### ISSUE TITLE
激活问题。

### ISSUE THREAD

**Issue by Bianfuchen** [veryyoung/WechatLuckyMoney#131]
为什么cm11安卓4.4.4无法激活这个插件？用的xposed是solarwarez修改的2.61版本的apk。请求能够解决。感谢

**Comment by veryyoung** [comment]
那这属于你第三方xposed 的问题了，不在本软件的谈了范畴。

**Comment by Bianfuchen** [comment]
你好，是这样的。我试过官版xposed2.61，发现你的qq红包和微信红包都无法激活。然后就换了solarwarez修改版的发现还是不行，你的随机游戏倒是都可以。很早以前我就发现了，是不是你的插件不兼容安卓4.x系统？

**Comment by goodjax** [comment]
请求大神帮我弄下这个插件，测试很多次都用不了

**Comment by veryyoung** [comment]
@goodjax 你没提供任何信息，我没法帮你。

**Comment by goodjax** [comment]
QQ的可以自动抢，微信的就不行微信版本试过几个自动抢不了什么反应都没，是不是不能装两个插件？

**Comment by Bianfuchen** [comment]
大佬确实是你这插件不支持安卓4.4。我看基佬安也有人反应这问题。
