### ISSUE TITLE
请问哪里能下载到可信的微信官方的历史版本

### ISSUE THREAD

**Issue by tarkky** [veryyoung/WechatLuckyMoney#132]
我去weixin.qq.com，然后找到他们的历史版本下载，但是点击下载都是最新版的6.5.14
网上搜了有很多下载的，但是，不太放心，请问能否推荐个比较放心的可以下载到非play版本的官方微信的历史版本的下载。谢谢。

**Comment by veryyoung** [comment]
@tarkky 不属于本软件的内容，不过我可以教你搜索下。第一步打开 google，第二步，搜索“微信历史版本”。

**Comment by goodjax** [comment]
请问谁有安卓逍遥2.7.2模拟器用的微信插件，基于Xposed的

**Comment by vipzrx** [comment]
@goodjax
模拟器只是再模拟手机,你要找的应该是逍遥能用的xposed框架吧?
