### ISSUE TITLE
微信 6.5.13 报错日志，帮忙看下，谢谢啦

### ISSUE THREAD

**Issue by Rnben** [veryyoung/WechatLuckyMoney#133]
09-12 08:26:55.998 I/Xposed  (  821): -----------------
09-12 08:26:55.998 I/Xposed  (  821): Starting Xposed version 87 (Xposed by PurifyOS), compiled for SDK 25
09-12 08:26:55.998 I/Xposed  (  821): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
09-12 08:26:55.998 I/Xposed  (  821): ROM: ONEPLUS A5000_23_170825
09-12 08:26:55.998 I/Xposed  (  821): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/08141919:user/release-keys
09-12 08:26:55.998 I/Xposed  (  821): Platform: arm64-v8a, 64-bit binary, system server: yes
09-12 08:26:55.998 I/Xposed  (  821): SELinux enabled: yes, enforcing: yes
09-12 08:26:57.012 I/Xposed  (  821): -----------------
09-12 08:26:57.012 I/Xposed  (  821): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-12 08:26:57.307 I/Xposed  (  821): Detected ART runtime
09-12 08:26:57.317 I/Xposed  (  821): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-12 08:26:57.517 I/Xposed  (  821): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1/base.apk
09-12 08:26:57.526 I/Xposed  (  821):   Loading class me.veryyoung.wechat.luckymoney.Main
09-12 08:27:06.329 I/Xposed  (  822): -----------------
09-12 08:27:06.329 I/Xposed  (  822): Starting Xposed version 87 (Xposed by PurifyOS), compiled for SDK 25
09-12 08:27:06.329 I/Xposed  (  822): Device: ONEPLUS A5000 (OnePlus), Android version 7.1.1 (SDK 25)
09-12 08:27:06.329 I/Xposed  (  822): ROM: ONEPLUS A5000_23_170825
09-12 08:27:06.329 I/Xposed  (  822): Build fingerprint: OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/08141919:user/release-keys
09-12 08:27:06.329 I/Xposed  (  822): Platform: arm64-v8a, 32-bit binary, system server: no
09-12 08:27:06.329 I/Xposed  (  822): SELinux enabled: yes, enforcing: yes
09-12 08:27:06.331 I/Xposed  (  822): -----------------
09-12 08:27:06.331 I/Xposed  (  822): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
09-12 08:27:06.623 I/Xposed  (  822): Detected ART runtime
09-12 08:27:06.631 I/Xposed  (  822): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
09-12 08:27:06.798 I/Xposed  (  822): Loading modules from /data/app/me.veryyoung.wechat.luckymoney-1/base.apk
09-12 08:27:06.806 I/Xposed  (  822):   Loading class me.veryyoung.wechat.luckymoney.Main
09-12 08:27:17.501 I/Xposed  ( 3059): Found wechat version:6.5.13
09-12 08:27:17.828 I/Xposed  ( 3260): Found wechat version:6.5.13
09-12 08:27:19.967 I/Xposed  ( 3815): Found wechat version:6.5.13
09-12 08:27:20.720 I/Xposed  ( 3904): Found wechat version:6.5.13
09-12 08:27:23.722 I/Xposed  ( 4097): Found wechat version:6.5.13
09-12 08:27:25.672 I/Xposed  ( 4180): Found wechat version:6.5.13
09-12 08:27:38.875 I/Xposed  ( 5231): Found wechat version:6.5.13
09-12 08:27:39.148 I/Xposed  ( 5266): Found wechat version:6.5.13
09-12 08:27:39.528 I/Xposed  ( 5316): Found wechat version:6.5.13
09-12 08:28:57.359 I/Xposed  ( 5231): Hid package: de.robv.android.xposed.installer
09-12 08:28:57.359 I/Xposed  ( 5231): Hid package: com.fkzhang.wechatxposed
09-12 08:28:57.359 I/Xposed  ( 5231): Hid package: me.veryyoung.wechat.luckymoney
09-12 08:29:14.805 I/Xposed  ( 6065): Found wechat version:6.5.13
09-12 08:29:17.906 I/Xposed  ( 6200): Found wechat version:6.5.13
09-12 08:30:51.853 E/Xposed  ( 5231): java.lang.NoSuchMethodError: com.tencent.mm.u.ap#vd()#bestmatch
09-12 08:30:51.853 E/Xposed  ( 5231): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:440)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:453)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1262)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at me.veryyoung.wechat.luckymoney.Main$1.afterHookedMethod(Unknown Source)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.e.b.ce.b(Unknown Source)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.storage.au.b(SourceFile:1578)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.storage.av.Am(SourceFile:991)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.storage.af.a(SourceFile:246)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.storage.av$1.o(SourceFile:310)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.sdk.e.k.bKA(SourceFile:166)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.sdk.e.k.unlock(SourceFile:47)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.storage.av.Aj(SourceFile:389)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.plugin.messenger.foundation.f.aY(SourceFile:107)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.plugin.zero.c.aY(SourceFile:70)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.modelmulti.r$a$1.oQ(SourceFile:746)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.sdk.platformtools.aj.handleMessage(SourceFile:69)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.sdk.platformtools.ag.handleMessage(SourceFile:173)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at com.tencent.mm.sdk.platformtools.ag.dispatchMessage(SourceFile:128)
09-12 08:30:51.853 E/Xposed  ( 5231): 	at android.os.Looper.loop(Looper.java:154)

**Comment by veryyoung** [comment]
@Rnben 升级到最新版
