### ISSUE TITLE
安卓4.3.1系统，软件不抢包

### ISSUE THREAD

**Issue by zzarking** [veryyoung/WechatLuckyMoney#142]
LG nexus4  刷了cm的系统。安卓版4.3.1， 安装了Xposed2.7.1的版本。。安装1.2.9之后，微信6.5.16 闪退。按照你的方法，设置好了，但软件不抢包，请问老大这是什么原因呢？    谢谢

**Comment by dacaiyeye** [comment]
好像不支持安卓5.0一下的   也不清楚   我另外一个手机4.4.4的 就没办法用   5.0的就可以。

**Comment by 1512275072** [comment]
我安卓4.4.4也不能抢红包 框架还是2.61的
