### ISSUE TITLE
红米Note1s增强版不能抢红包

### ISSUE THREAD

**Issue by 1512275072** [veryyoung/WechatLuckyMoney#147]
我的手机版本是4.4.4 微信版本是6.516  红包软件最新的。其他插件有用！ 请问哪里出现问题？去年过年还能试用改软件，软件更新更新着就不能试用！

**Comment by 1512275072** [comment]
作者？？

**Comment by veryyoung** [comment]
@1512275072 用最新版的试试吧，老版本的不一定是兼容的，挨个版本测试太麻烦了
