### ISSUE TITLE
大哥自动收钱能不能加一个

### ISSUE THREAD

**Issue by kanakey** [veryyoung/WechatLuckyMoney#150]
我是做快递的，现在发红包的不多了，经常是转账忘记，能不能弄个自动收钱的功能

**Comment by veryyoung** [comment]
@kanakey 可以考虑哦，谢谢你的意见。

**Comment by veryyoung** [comment]
@kanakey 已经 OK 拉，你可以去酷市场或者到 xposed 仓库去下载哦

**Comment by kanakey** [comment]
大哥我升级了反而还失效了，不但不能自动收钱现在连自动收钱都没了

**Comment by kanakey** [comment]
大哥我升级了反而还失效了，不但不能自动收钱现在连自动领红包都没了

**Comment by veryyoung** [comment]
@kanakey 升级完需要重启的，同时微信也得是最新版本。

**Comment by kanakey** [comment]
我一直用的6.5.10，我看酷安介绍里支持这个版本啊，大哥能兼容一下吗，如果不行也没关系

**Comment by veryyoung** [comment]
@kanakey 直接用 6.6.0 哦，最新版本一般支持最好的。

**Comment by kanakey** [comment]
真的不行，升级了6.6也不行，是要最新版吗？

**Comment by kanakey** [comment]
安卓4.4不行吗，另外一个6.0的手机没试

**Comment by veryyoung** [comment]
@kanakey 都要最新版的，微信和插件。

**Comment by veryyoung** [comment]
@kanakey 不好意思，确实是有个bug，已经修复了

**Comment by kanakey** [comment]
大哥辛苦了，现在没有免打扰不抢这个选项了吗
