### ISSUE TITLE
小米手机上没反应

### ISSUE THREAD

**Issue by zkjmyy** [veryyoung/WechatLuckyMoney#153]

**Comment by veryyoung** [comment]
@zkjmyy please provide more details

**Comment by zkjmyy** [comment]
@veryyoung 按照你的代码跑起来，应该就可以自己抢红包，但我试了，并没有.7.0.1手机mui9.小米4c测试的。更详细的我不知道怎么提供了。关键没反应

**Comment by yejun556688** [comment]
我在小米手机上也没有反映

**Comment by veryyoung** [comment]
基于 xposed 的哦朋友。手写得确保 xposed 正确运作。

**Comment by sunshine61** [comment]
我的小米也没反应  ，MIUI9.1，微信版本6.62，小米5

**Comment by yusureabc** [comment]
米6  MIUI9.2.4  无效

**Comment by yusureabc** [comment]
@sunshine61 我重新刷机的 开发版的MIUI  安卓7.1  才可以的

**Comment by nanyuweiyi** [comment]
小米手机没反应
