### ISSUE TITLE
依然不支持Android7吗？

### ISSUE THREAD

**Issue by Naolador** [veryyoung/WechatLuckyMoney#154]
升级到7版本后插件就失效了，xposed已经安装了最新版本。是这个插件尚未适配吗？

**Comment by veryyoung** [comment]
@Naolador 适配的哦，我这边测试是 OK 的

**Comment by Naolador** [comment]
@veryyong 谢谢如此快的回复。有什么办法看log吗？我在xposed下的log里面始终看到的是空白的。

**Comment by veryyoung** [comment]
@Naolador 是空白的日志，代表应该是没问题的。

**Comment by Naolador** [comment]
又升级了xposed终于可以了，谢谢。

**Comment by Freedom000** [comment]
现在支持6.6.1吗 另外安卓系统支持7.1.1吗
