### ISSUE TITLE
微信6.6.0又找不到dex文件了，快更新。。。

### ISSUE THREAD

**Issue by 287257255** [veryyoung/WechatLuckyMoney#155]
Found wechat version:6.6.0
12-27 16:47:54.203 E/Xposed  ( 6741): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.ui.En_fba4b94f

**Comment by veryyoung** [comment]
已支持
