### ISSUE TITLE
6.6.0别人发红包不能自动抢

### ISSUE THREAD

**Issue by BreakZero** [veryyoung/WechatLuckyMoney#157]
微信版本6.6.0只能收到自己发的红包

**Comment by BreakZero** [comment]
跟#159 提的是一个问题

**Comment by veryyoung** [comment]
@BreakZero  supportted
 https://github.com/veryyoung/WechatLuckyMoney/commit/932d16864941fa6ca2b53b7cbce868cfc4b136d9
