### ISSUE TITLE
增加一个通知功能

### ISSUE THREAD

**Issue by B0y1n4o4** [veryyoung/WechatLuckyMoney#158]
希望能够添加一个抢到红包多少, 或者收到账多少，从哪个群，或者哪个人。通知栏发出一条通知.

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba

**Comment by B0y1n4o4** [comment]
@MZCretin 这个accessbility我自己也写了一个，不过notification的通知好像不管用了，文章是利用resource-id来识别抢红包的，但是微信已更新，哪怕只是一个小更新,这个值就会变化，app就会失效，我是通过文字识别来判断的，不过也有bug....

**Comment by MZCretin** [comment]
@B0y1n4o4    要说准确性，肯定是id来的要准确些，打个比方：你根据[微信红包]文字找，如果我发一个这样的文本你就会认为有红包，其实没有，再者，通过十几个微信的版本迭代规律来看，其实文字也在变化，所以无论用哪种方式，都要通过请求接口来更新本地配置文件，而不是写死。我目前就是这样做的，服务器会提供最近16个版本的微信id列表，app启动的时候会拉取对应的配置文件，然后实现微信有新版本的时候用户在无感知的情况下就能实现id的更新。

**Comment by B0y1n4o4** [comment]
@MZCretin 对的，方便公开源码嘛.

**Comment by MZCretin** [comment]
博客里面提供的代码已经完全足够实现了  跟源码没什么区别的  博客里面的apk因为有自己后台接口的调用  不方便开源

**Comment by MZCretin** [comment]
@B0y1n4o4 博客里面提供的代码已经完全足够实现了 跟源码没什么区别的 博客里面的apk因为有自己后台接口的调用 不方便开源
