### ISSUE TITLE
没有任何反应

### ISSUE THREAD

**Issue by a843647878** [veryyoung/WechatLuckyMoney#161]
不知道是我操作不对还是怎么样   一加3和三星S7  都没有反应  WX版本是6.6.0和6.6.1

**Comment by Freedom000** [comment]
安卓系统版本是多少？

**Comment by a843647878** [comment]
三星S7是6.0.1   一加3是7.0

**Comment by veryyoung** [comment]
基于 xposed 的，各位

**Comment by a843647878** [comment]
也就是说我需要root手机并安装XP框架是吧？

**Comment by veryyoung** [comment]
@a843647878 必须项

**Comment by CAndJava1** [comment]
锁屏，息屏都可以自动抢吗？

**Comment by veryyoung** [comment]
@CAndJava1 Test it by yourself, test before ask, ok?

**Comment by CAndJava1** [comment]
Black screen, can't snatch @veryyoung

**Comment by yaoshanliang** [comment]
Black screen, can't snatch
