### ISSUE TITLE
无效

### ISSUE THREAD

**Issue by huanggongyao** [veryyoung/WechatLuckyMoney#162]
三星S7,三星S6edge,三星on7都没有反应，是不是操作姿势不对？

**Comment by Freedom000** [comment]
你安卓系统版本是多少？

**Comment by veryyoung** [comment]
基于 xposed

**Comment by js-beginner** [comment]
> 基于 xposed

是要下载xposed才能用？

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
