### ISSUE TITLE
微信6.6.1无反应

### ISSUE THREAD

**Issue by citymaster** [veryyoung/WechatLuckyMoney#167]
我看到模块1.3.4只支持到微信6.6.0，但是看到13天前代码已经增加了6.6.1版本的支持，所以我想确认下1.3.4是不是真的不支持6.6.1，然后想问下什么时候能支持？是不是现在6.6.1的版本还没稳定？有相应的测试版本吗？

**Comment by citymaster** [comment]
==补充下环境==
手机型号：nubia z17
微信：6.6.1
安卓系统：7.1.1
Xpose Installer：3.1.4
Xpose框架：v87
红包插件：1.3.4
====XP日志===
Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log(No such file or directory)
====现象=====
收到红包插件无任何动作。

**Comment by veryyoung** [comment]
@citymaster 支持的。

你这边没有提供任何有信息的日志哦，建议把日志先搞出来。

**Comment by muyl** [comment]
我的也不好使

**Comment by citymaster** [comment]
@veryyoung 我也想提供有用的log:( 但是一直提示这个：
Cannot read log/data/user_de/0/de.robv.android.xposed.installer/log/error.log(No such file or directory)
后面我去这个目录下创建一个error.log文件，结果一直返回：
日志为空
---

**Comment by muyl** [comment]
@citymaster 不一样 我的是华为

**Comment by citymaster** [comment]
@veryyoung 能不能像微X模块一样，界面提示模块没有运行，最好是能提示那些条件没有满足什么的，哈哈，我是感觉什么都没反应有点郁闷无从下手了。root也成功了，框架也激活了，插件也支持微信了，不知道差哪了哪了，xposed第一次入坑-.-

**Comment by citymaster** [comment]
哦，还有一个现象，点微信捐赠没反应？点支付宝捐赠是可以的，是不是微信支持应用分身影响的没有识别对微信？

**Comment by citymaster** [comment]
高兴！！终于可以用了~
更新了下框架到v88.2(nubia和小米的貌似不能刷官方的，需要特别定制，之前我刷v89的卡开机界面了)，就可以用啦，然后点微信捐赠有效啦 :)  这是用于版本测试的后门吗

**Comment by X-Mars** [comment]
大佬  华为mate9  可以安装框架吗

**Comment by X-Mars** [comment]
大佬  华为mate9  可以安装框架吗

**Comment by citymaster** [comment]
@X-Mars 可以的，你可以去华为Mate9论坛搜索xposed相关的帖子，里面有相关的教程，这样手机不容易变砖，这个教程挺好，你可以参考：http://club.huawei.com/thread-13903675-1-1.html

**Comment by X-Mars** [comment]
@citymaster 谢谢大佬，好像需要刷机。我要在考虑下
