### ISSUE TITLE
最新版1.04卡微信

### ISSUE THREAD

**Issue by 514186** [veryyoung/WechatLuckyMoney#17]
MIUI8.0，6.322微信用最新版1.04卡

**Comment by itlijiang** [comment]
我的也是这样，也收不到信息，相当于断网，关闭插件就好了

**Comment by veryyoung** [comment]
@514186 @itlijiang  参考 https://github.com/veryyoung/WechatLuckyMoney/issues/13

**Comment by itlijiang** [comment]
微信不闪退的，就是卡住了

**Comment by itlijiang** [comment]
也收不到信息了

**Comment by itlijiang** [comment]
我的找不到那个文件，刚刚启动插件又好了

**Comment by 514186** [comment]
需要用re管理器才能看到

**Comment by itlijiang** [comment]
是用re,但是没有最后的那个文件，
