### ISSUE TITLE
微信6.5.23没有反应，用的2.7 Xposed 日志报找不到类，该如何解决

### ISSUE THREAD

**Issue by xwj123380** [veryyoung/WechatLuckyMoney#170]
微信6.5.23没有反应，用的2.7 Xposed 日志报找不到类，该如何解决
no class found:com.tencent.mm.plugin.collect.reward.ui.QrRewardSelectMoneyUI

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
