### ISSUE TITLE
关于指定id不抢

### ISSUE THREAD

**Issue by AtlantisWing** [veryyoung/WechatLuckyMoney#171]
问下能否指定群名不抢？有些是工作群同事转饭钱什么的，自动抢了影响不好

**Comment by veryyoung** [comment]
@AtlantisWing 可以使用指定 ID 不抢功能

**Comment by AtlantisWing** [comment]
恩，我知道指定id不抢，只是群里人有点多，一个个指定要几十个人，手机上不太好操作啊，能否已群id或者群名字作为过滤？thx～

**Comment by veryyoung** [comment]
@AtlantisWing 把群 ID放进去就行了。

**Comment by AtlantisWing** [comment]
我试了下,好像无法获取到群id,只能看到群名字,尝试用名字过滤无效

**Comment by veryyoung** [comment]
@AtlantisWing 打开显示ID 的选项。

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
