### ISSUE TITLE
用这个会不会导致微信被封号？

### ISSUE THREAD

**Issue by hucaloof** [veryyoung/WechatLuckyMoney#173]
春节马上到了，各个微信群里面红包抢不停，就是不知道会不会被封号。

**Comment by veryyoung** [comment]
@hucaloof 会不会封不是插件说了算，而是TX能不能检测出来，检测出来会不会 block 的问题。

**Comment by mrLiwg** [comment]
@hucaloof @veryyoung 请问这个是怎么使用的啊
