### ISSUE TITLE
V大，是不是还没有支持8.0的系统？

### ISSUE THREAD

**Issue by beney84** [veryyoung/WechatLuckyMoney#176]
如题，8.1 AOSP安装无效 :(

**Comment by jupitors** [comment]
我的8.1 APOS ，XP框架3.1.5，微信6.6.1 ，没有反应。

**Comment by beney84** [comment]
我已经改用微x模块了，也能抢。。




取得 Outlook for Android







On Tue, Feb 6, 2018 at 12:55 PM +0800, "jupitors" <notifications@github.com> wrote:












我的8.1 APOS ，XP框架3.1.5，微信6.6.1 ，没有反应。

**Comment by veryyoung** [comment]
@beney84 这应该和操作系统版本没有关系，和 XP 是否 work 有关系。

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
