### ISSUE TITLE
4.4.x机器无效

### ISSUE THREAD

**Issue by sishuixianghuo** [veryyoung/WechatLuckyMoney#177]
4.4.x 上好多机器用不了。我这边已经适配了，求大神给个权限提交一下代码
代码贴在下面了。

**Comment by artemiseven** [comment]
我也是在4.4.x上miui机器测试.
看了下log , 好像报错了,你那边是怎么解决的吗? 可以学习下吗? @sishuixianghuo 谢谢了

I/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.b.af
                                                                  at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
                                                                  at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
                                                                  at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Main.java:106)

**Comment by sishuixianghuo** [comment]
public static void handler(final XC_LoadPackage.LoadPackageParam loadPackageParam) {
			try {
				PackageInfo packageInfo = getContext().getPackageManager().getPackageInfo(loadPackageParam.packageName, 0);
				WXVersionParam.init(packageInfo.versionName);
				if (Build.VERSION.SDK_INT > 20 || packageInfo.versionCode < 1200) {
					try {
						XposedHelpers.findAndHookMethod(Application.class, "attach", new Object[]{Context.class, new XC_MethodHook() {

							@Override
							protected void afterHookedMethod(MethodHookParam methodHookParam) {
								final Context context = (Context) methodHookParam.args[0];
								handlerClass(context.getClassLoader());
							}
						}});
					} catch (SecurityException e2) {
						XposedHelpers.findAndHookMethod("android.app.Application", loadPackageParam.classLoader, "onCreate", new Object[]{new XC_MethodHook() {

							@Override
							protected void afterHookedMethod(MethodHookParam methodHookParam) {
								Context context = (Context) methodHookParam.thisObject;
								handlerClass(context.getClassLoader());
							}
						}});
					} catch (Exception e3) {
						e3.printStackTrace();
					} catch (Error e4) {
						e4.printStackTrace();
					}
				} else {
					XposedHelpers.findAndHookMethod(Application.class, "attach", new Object[]{Context.class, new XC_MethodHook() {

						@Override
						protected void afterHookedMethod(MethodHookParam methodHookParam) {
							final Context context = (Context) methodHookParam.args[0];
							new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
								@Override
								public void run() {
									handlerClass(context.getClassLoader());
								}
							}, 2000);

						}
					}});
					XposedHelpers.findAndHookMethod("android.app.Application", loadPackageParam.classLoader, "onCreate", new Object[]{new XC_MethodHook() {

						@Override
						protected void afterHookedMethod(MethodHookParam methodHookParam) {
							Context context = (Context) methodHookParam.thisObject;
							handlerClass(context.getClassLoader());
						}
					}});
				}

			} catch (PackageManager.NameNotFoundException e) {
				e.printStackTrace();
			}
		}


		private static void handlerClass(final ClassLoader loader) {
			Log.e(TAG, "handlerClass unhook = " + unhook + ", unhook2 = " + unhook2);
			if (unhook == null) {

				unhook = XposedHelpers.findAndHookMethod("com.tencent.wcdb.database.SQLiteDatabase", loader, "insert", String.class, String.class, ContentValues.class, new XC_MethodHook() {
					@Override
					protected void afterHookedMethod(MethodHookParam param) throws Throwable {
						ContentValues contentValues = (ContentValues) param.args[2];
						String tableName = (String) param.args[0];
						if (TextUtils.isEmpty(tableName) || !tableName.equals("message")) {
							return;
						}
						Integer type = contentValues.getAsInteger("type");
						if (null == type) {
							return;
						}
						if (type == 436207665 || type == 469762097) {
							handleLuckyMoney(contentValues, loader);
						} else if (type == 419430449) {
							handleTransfer(contentValues, loader);
						}
					}
				});
			}
			if (unhook2 == null) {
				unhook2 = findAndHookMethod(WXVersionParam.receiveLuckyMoneyRequest, loader, "a", int.class, String.class, JSONObject.class, new XC_MethodHook() {
							@Override
							protected void beforeHookedMethod(MethodHookParam param) throws JSONException {
								if (!WXVersionParam.hasTimingIdentifier) {
									return;
								}
								if (messages.size() <= 0) {
									return;
								}

								String timingIdentifier = ((JSONObject) (param.args[2])).getString("timingIdentifier");
								String sendid = ((JSONObject) (param.args[2])).getString("sendId");

								if (TextUtils.isEmpty(timingIdentifier) || TextUtils.isEmpty(sendid)) {
									return;
								}
								LuckyMoneyMessage luckyMoneyMessage = messages.get(sendid);
								Object luckyMoneyRequest = XposedHelpers.newInstance(XposedHelpers.findClass(WXVersionParam.luckyMoneyRequest, loader),
										luckyMoneyMessage.getMsgType(), luckyMoneyMessage.getChannelId(), luckyMoneyMessage.getSendId(), luckyMoneyMessage.getNativeUrlString(), "", "", luckyMoneyMessage.getTalker(), "v1.0", timingIdentifier);
								callMethod(requestCaller, "a", luckyMoneyRequest, 1000);
	//                            luckyMoneyMessages.remove(0);
								messages.remove(sendid);
							}
						}
				);
			}
		}

**Comment by artemiseven** [comment]
WXVersionParam.receiveLuckyMoneyRequest 你设置的是多少啊

**Comment by sishuixianghuo** [comment]
没改啊，都是他源码设置的啊

**Comment by veryyoung** [comment]
@sishuixianghuo 是取  context 的方式不同吗？

**Comment by artemiseven** [comment]
可以了，多谢大神啊， 原理是什么啊 ？不是很清楚，是不是延时了一下啊 ，我开始一直以为是某个类在4.x上找不到，反编译看调用应该还是和5.x一样，

**Comment by gassion** [comment]
大神就是败类

**Comment by sishuixianghuo** [comment]
@veryyoung    反编译脱壳有没有什么好的资料，求指导一下。
@artemiseven 
这是getContext
    public static Context getContext() {
        return (Context) XposedHelpers.callMethod(XposedHelpers.callStaticMethod(XposedHelpers.findClass("android.app.ActivityThread", ClassLoader.getSystemClassLoader()), "currentActivityThread", new Object[0]), "getSystemContext", new Object[0]);
    }

**Comment by gassion** [comment]
@sishuixianghuo  大神源码确实好用……

**Comment by artemiseven** [comment]
脱壳看过一篇简单文章，不知道是否对你有帮助
@sishuixianghuo 
http://www.wjdiankong.cn/apk%E8%84%B1%E5%A3%B3%E5%9C%A3%E6%88%98%E4%B9%8B-%E8%84%B1%E6%8E%89360%E5%8A%A0%E5%9B%BA%E7%9A%84%E5%A3%B3/

**Comment by LessMo** [comment]
@sishuixianghuo 麻烦能加个完成的 PR 吗？

**Comment by sishuixianghuo** [comment]
@LessMo  还要吗。留下邮箱单独发你吧

**Comment by LessMo** [comment]
@sishuixianghuo 524262909@qq.com 多谢 👍

**Comment by chinese-tea** [comment]
@sishuixianghuo 
我的手机是4.4.2用不了这个插件，能否给个能用的？
