### ISSUE TITLE
你好 作者 我是最新版的使用者 微信使用的6.6.2  无法正常抢红包

### ISSUE THREAD

**Issue by lbxw** [veryyoung/WechatLuckyMoney#179]

**Comment by srctar** [comment]
我刚刚把 app 文件夹下面的 app-release.apk 安装到我的 7.1.1 里面去。 就收到了一个群红包， 但是。 没有自动抢。。。。。。。。。

**Comment by lbxw** [comment]
是的 我也是没有自动抢  根本没反应。

**Comment by Jorgejie** [comment]
是的,感觉和没装一样

**Comment by hadesjaky** [comment]
我的也是  而且 微信ID也不显示

**Comment by JamesLebron** [comment]
你好，最新的微信6.6.2 确实不能抢红包了

**Comment by CoterJiesen** [comment]
试了微信6.6.2  也不行

**Comment by BlueTearsY** [comment]
各位哥哥，鄙人测试，需要将旧版本卸载后重新安装支持微信6.6.2的1.3.5版本，重启手机后就可以用了

**Comment by xuqingfu** [comment]
我在Xposed中激活了该插件，但是似乎并没有用，根本不会自动抢
