### ISSUE TITLE
Nexus 5X 安卓7.1.2 微信不能抢红包

### ISSUE THREAD

**Issue by chunyuong** [veryyoung/WechatLuckyMoney#181]
如题，xposed x89框架 正常，但是不能抢红包

**Comment by chunyuong** [comment]
我的微信是6.5.24，升级到6.6.2 也不行

**Comment by chunyuong** [comment]
刚试了一下 1.3.4版本可以。1.3.5版本不可以，问一下，那个快速拆包是干嘛的？

**Comment by veryyoung** [comment]
@chunyuong 就是不需要点”拆“那个字，用来手工抢红包，。

**Comment by chunyuong** [comment]
@veryyoung  但是即使我把那个关了，依然后自动抢的。不需要手动点击”拆“字。

**Comment by veryyoung** [comment]
@chunyuong 想手工拆，需要把自动的开关关掉

**Comment by chunyuong** [comment]
懂了 ，谢谢
