### ISSUE TITLE
Google Play 6.6.2 无效，日志如下

### ISSUE THREAD

**Issue by narcotics726** [veryyoung/WechatLuckyMoney#187]
02-15 15:52:35.850 I/Xposed  (12088): Found wechat version:6.6.2
02-15 15:52:35.866 E/Xposed  (12088): java.lang.NoSuchMethodError: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI#d(int,int,java.lang.String,com.tencent.mm.ad.k)#exact
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
02-15 15:52:35.866 E/Xposed  (12088): 	at me.veryyoung.wechat.luckymoney.Main.handleLoadPackage(Unknown Source)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.os.Looper.loop(Looper.java:154)
02-15 15:52:35.866 E/Xposed  (12088): 	at android.app.ActivityThread.main(ActivityThread.java:6422)
02-15 15:52:35.866 E/Xposed  (12088): 	at java.lang.reflect.Method.invoke(Native Method)
02-15 15:52:35.866 E/Xposed  (12088): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-15 15:52:35.866 E/Xposed  (12088): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-15 15:52:35.866 E/Xposed  (12088): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by narcotics726** [comment]
切换回 6.6.1 后一切正常，插件版本 1.3.5

**Comment by veryyoung** [comment]
嗯，使用新版本。
