### ISSUE TITLE
有个诡异的现象，前台可以抢包，后台不能抢，不知道什么原因

### ISSUE THREAD

**Issue by ohyeah521** [veryyoung/WechatLuckyMoney#189]
Oneplus 5T Android7.1.1   关闭doze模式也不行，不知道什么原因

**Comment by veryyoung** [comment]
我是一加3，貌似没有出现不抢的现象。

**Comment by chunyuong** [comment]
我也出现过，主要是抢群红包出现的概率比较大。我用的是nexus 5X

**Comment by sishuixianghuo** [comment]
理论上只要能收到信息就能抢红包

**Comment by yusureabc** [comment]
消息免打扰的群红包确实会抢不到，在待机状态下，我的是 米6  MIUI9  安卓7.1
