### ISSUE TITLE
日志一直抛出error

### ISSUE THREAD

**Issue by aviraxp** [veryyoung/WechatLuckyMoney#19]
07-09 23:11:58.753 E/Xposed  ( 6725): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
07-09 23:11:58.753 E/Xposed  ( 6725): 	at me.veryyoung.wechat.luckymoney.Main$1.afterHookedMethod(Main.java:47)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.e.b.bj.b(<Xposed>)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.storage.ai.b(SourceFile:1500)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.storage.aj.c(SourceFile:1680)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.i(SourceFile:878)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.a(SourceFile:587)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a$2.e(SourceFile:672)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.ImageGalleryUI$13$1$1.run(SourceFile:621)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ai.run(SourceFile:127)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at android.os.Handler.handleCallback(Handler.java:739)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ae.dispatchMessage(SourceFile:117)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at android.os.Looper.loop(Looper.java:148)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at java.lang.reflect.Method.invoke(Native Method)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-09 23:11:58.753 E/Xposed  ( 6725): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-09 23:11:58.756 E/Xposed  ( 6725): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
07-09 23:11:58.756 E/Xposed  ( 6725): 	at me.veryyoung.wechat.luckymoney.Main$1.afterHookedMethod(Main.java:47)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.e.b.bj.b(<Xposed>)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.storage.ai.b(SourceFile:1500)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.storage.aj.c(SourceFile:1680)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.i(SourceFile:878)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.a(SourceFile:587)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a$2.e(SourceFile:672)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.ImageGalleryUI$13$1$1.run(SourceFile:621)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ai.run(SourceFile:127)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at android.os.Handler.handleCallback(Handler.java:739)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ae.dispatchMessage(SourceFile:117)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at android.os.Looper.loop(Looper.java:148)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at java.lang.reflect.Method.invoke(Native Method)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-09 23:11:58.756 E/Xposed  ( 6725): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-09 23:11:58.757 E/Xposed  ( 6725): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
07-09 23:11:58.757 E/Xposed  ( 6725): 	at me.veryyoung.wechat.luckymoney.Main$1.afterHookedMethod(Main.java:47)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:348)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.e.b.bj.b(<Xposed>)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.storage.ai.b(SourceFile:1500)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.storage.aj.c(SourceFile:1680)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.i(SourceFile:878)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a.a(SourceFile:587)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.b$a$2.e(SourceFile:672)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.ui.chatting.gallery.ImageGalleryUI$13$1$1.run(SourceFile:621)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ai.run(SourceFile:127)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at android.os.Handler.handleCallback(Handler.java:739)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.tencent.mm.sdk.platformtools.ae.dispatchMessage(SourceFile:117)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at android.os.Looper.loop(Looper.java:148)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at java.lang.reflect.Method.invoke(Native Method)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-09 23:11:58.757 E/Xposed  ( 6725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by xfunforx** [comment]
应该是日志中要输出一个对象时没判断是否为空，直接toString了。问题不大。

String content = getObjectField(param.thisObject, "field_content").toString();
String talker = getObjectField(param.thisObject, "field_talker").toString();

应该是这两个里面有一项为null了，直接toString所以才报那个错误。

从日志上看好像是接收到图片的原因。

07-09 23:11:58.753 E/Xposed ( 6725): at com.tencent.mm.ui.chatting.gallery.b$a.i(SourceFile:878)
07-09 23:11:58.753 E/Xposed ( 6725): at com.tencent.mm.ui.chatting.gallery.b$a.a(SourceFile:587)
07-09 23:11:58.753 E/Xposed ( 6725): at com.tencent.mm.ui.chatting.gallery.b$a$2.e(SourceFile:672)
07-09 23:11:58.753 E/Xposed ( 6725): at com.tencent.mm.ui.chatting.gallery.ImageGalleryUI$13$1$1.run(SourceFile:621)

图片这些地方跟红包没有任何关系，不知道为何与 com.tencent.mm.e.b.bj.b 有关？？？

**Comment by veryyoung** [comment]
@xfunforx 你分析得很有道理。

我应该先判断类型，再去取 content 的。

我平时插件根本不开，没测到图片这种情况，所以没盯到错误日志。
