### ISSUE TITLE
关于插件中“Setting”的实现

### ISSUE THREAD

**Issue by XF-zhjnc** [veryyoung/WechatLuckyMoney#192]
求助：在[SettingActivity $ SettingsFragment](https://github.com/veryyoung/WechatLuckyMoney/blob/master/app/src/main/java/me/veryyoung/wechat/luckymoney/SettingsActivity.java)中， `getPreferenceManager().setSharedPreferencesMode(MODE_WORLD_READABLE)` 这段代码的 `MODE_WORLD_READABLE` 这个存储方式已经不可用了，编译提示 `java.lang.SecurityException: MODE_WORLD_READABLE no longer supported` ，请问大神有什么解决方法吗？

**Comment by veryyoung** [comment]
只能用这个模式，不然微信是没法读取咱们应用的 sharedPreference 的。

**Comment by aviraxp** [comment]
https://github.com/bin456789/Unblock163MusicClient-Xposed/blob/521f94ee9a5a88a4f24d24171b4425ad75534c15/app/src/main/java/bin/xposed/Unblock163MusicClient/ui/SettingsActivity.java#L93

**Comment by XF-zhjnc** [comment]
原来如此，明白了，感谢两位
