### ISSUE TITLE
【not working】Android 8.1 Oreo + Xposed 90-beta3 +WechatLuckyMoney 1.3.6

### ISSUE THREAD

**Issue by jiebozhang** [veryyoung/WechatLuckyMoney#196]
Android 8.1 Oreo + Xposed 90-beta3 +WechatLuckyMoney 1.3.6+微信6.6.5

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
