### ISSUE TITLE
现有版本是否已经不支持抢群红包功能？

### ISSUE THREAD

**Issue by Naolador** [veryyoung/WechatLuckyMoney#199]
插件安装正常。可以立即自动接收个人发来的红包和转账。

但是群内发的红包不会自动打开，即使关闭延时也无效。请问是不是现有插件已经关闭的抢群红包功能？

**Comment by veryyoung** [comment]
@Naolador 经测试没问题。

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
