### ISSUE TITLE
激活本模块后会使微信闪退

### ISSUE THREAD

**Issue by 443289353** [veryyoung/WechatLuckyMoney#20]
激活后微信会无限闪退，禁用此模块后一切正常，望作者尽快修复！

**Comment by 443289353** [comment]
尴尬，刚刚试了https://github.com/veryyoung/WechatLuckyMoney/issues/13中作者提供的方法，激活重启后微信一切正常了，初步判断是微信的热补丁(tinker)中采取了一些措施使微信在被修改的情况下无法正常运行

**Comment by veryyoung** [comment]
@443289353 赞！
