### ISSUE TITLE
红米手机没反应

### ISSUE THREAD

**Issue by wugezuiweiwu** [veryyoung/WechatLuckyMoney#200]
安卓版本4.4.4，微信版本6.6.6，xp框架安装好了，其他插件都可以，就是抢红包没反应

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
