### ISSUE TITLE
没有任何反应

### ISSUE THREAD

**Issue by hahsbdb** [veryyoung/WechatLuckyMoney#203]
xp框架已经启用模块也重启了，家里两台机子都试了，没反应

**Comment by hahsbdb** [comment]
求适配，一部一台夏新a918t系统4.4.2，一部夏普306sh系统4.4.4

**Comment by Freedom000** [comment]
@hahsbdb 我这边也是这样，没有反应。一加5  android7.1

**Comment by veryyoung** [comment]
4.X 的机子没测试过，这年头不都是 6、7、8 的机型吗？

**Comment by hahsbdb** [comment]
@veryyoung 
4.4和5.0应该还是有很多的吧，我看有不少才一年的机子还是5.x，微信现在也在兼容着4.2系统。

**Comment by hahsbdb** [comment]
我弄了个5.x的机子，正常运行，cm的系统

**Comment by Freedom000** [comment]
@veryyoung 我这边是一加5，安卓7.1  之前微信6.6.6和6.6.5都没问题  最新适配版6.6.7没反应  不抢红包...

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
