### ISSUE TITLE
miui Android4.4.4没有反应

### ISSUE THREAD

**Issue by 1016797313** [veryyoung/WechatLuckyMoney#206]
微信版本6.6.0
插件版本1.3.8
安卓4.4.4
手机是vivo刷的miui

**Comment by veryyoung** [comment]
基于 xposed 的

**Comment by 1016797313** [comment]
xp装了，而且勾选了，重启过了。。

**Comment by 1016797313** [comment]
@veryyoung

**Comment by veryyoung** [comment]
@1016797313 4.X 的手机不支持的，什么年代了...

**Comment by Freedom000** [comment]
@veryyoung 一加5 android7.1.1   XP89  之前一直用着没问题  微信升级6.6.7   你的这个插件，升级到了1.3.8 最近刚刚升级 该重启的都重启了，试了很多次了  目前对红包没反应  不知道，是我这里单独的问题，还是，6.6.7没有兼容好。

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
