### ISSUE TITLE
群聊开启免打扰不能抢

### ISSUE THREAD

**Issue by mengzhilian07** [veryyoung/WechatLuckyMoney#21]
问问作者能不能实现群聊免打扰也可以抢，要不群消息实在太多，手表电池不够用，一直震动，哈哈……
如果下版支持就好了，弱弱的问句，下版什么时候发？end！

**Comment by veryyoung** [comment]
@mengzhilian07 
免打扰是可以抢的。

下版发布时间是微信更新之后。

**Comment by mengzhilian07** [comment]
今天早上开始一点红包微信就提示为了帐号安全吧啦吧啦，然后就让重新登录。准备退回6.3.18用1.0.2。1.0.2支持群消息免打扰抢么？

**Comment by veryyoung** [comment]
@mengzhilian07 不支持，谢谢。

**Comment by mengzhilian07** [comment]
谢谢回复，都反映不能用了，吴大的也不能用。

**Comment by gMan1990** [comment]
不能抢免打扰的。今天刚试过
