### ISSUE TITLE
大佬帮忙看看

### ISSUE THREAD

**Issue by bxl0608** [veryyoung/WechatLuckyMoney#216]
最近有个需求，需要过微信的版本检测，6.6.7的版本不能注册微信，能不能把他检测版本的地方限制给去掉，能解决的话666红包，不多，小本生意，求帮帮忙！

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba
