### ISSUE TITLE
昨天开始只要抢包就被TX强制退出重新登录！

### ISSUE THREAD

**Issue by 1977helj** [veryyoung/WechatLuckyMoney#22]
如何破解

**Comment by veryyoung** [comment]
@1977helj 没发现诶，我用得挺好的啊

**Comment by mengzhilian07** [comment]
确实很多人被强制下线，作者是否对微信隐藏了红包插件？或者禁止了读取软件权限？

**Comment by aviraxp** [comment]
隐藏了。

我补充一句，所有应用都可以直接在用户层禁止xposed插件作用于自身，最多只能handle before method，所以微信想封，分分钟的事。

**Comment by 1977helj** [comment]
@veryyoung 真的有这个现象哈！另外说一句作者是否可以添加一下有XX关键字的红包不抢的功能？比如'测挂'这样的。

**Comment by mengzhilian07** [comment]
关屏状态下开启消息免打扰的群不会抢。
