### ISSUE TITLE
微信7.0新版本出现LuckyMoneyNotHookReceiveUI

### ISSUE THREAD

**Issue by wxudongCode** [veryyoung/WechatLuckyMoney#222]
微信7.0不能用，能帮忙看下吗

**Comment by MZCretin** [comment]
这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验app。https://juejin.im/post/5a7e857a51882528b63ff1ba

**Comment by AndroidJohnsonWang** [comment]
> 这个是动态支持微信版本的，已经支持微信7.0了，觉得挺好用的，文章中有下载链接可以体验的应用程序。https://juejin.im/post/5a7e857a51882528b63ff1ba

试了，微信7.0并没有效果

**Comment by MZCretin** [comment]
能否提供下 手机型号 系统版本
