### ISSUE TITLE
求大佬适配微信7.0.3

### ISSUE THREAD

**Issue by freeaday** [veryyoung/WechatLuckyMoney#226]
微信7.0好像有bug，某些型号手机一直卡死。内侧更新了一个7.0.3没事。求大佬适配微信7.0.3

**Comment by veryyoung** [comment]
@freeaday 正式版了就更新

**Comment by bys-alvin-wei** [comment]
nice good job

**Comment by Qinsin** [comment]
膜拜大神!!!!!

**Comment by Qinsin** [comment]
膜拜大神,请上7.0.3的更新版

**Comment by bys-alvin-wei** [comment]
haha,春节抢红包

**Comment by oumygod** [comment]
微信7.0 打开了自动抢红包 但是 不自动抢红包  手动点红包 会自动拆  咋回事呀 1.42

**Comment by showpro** [comment]
> 微信7.0 打开了自动抢红包 但是 不自动抢红包 手动点红包 会自动拆 咋回事呀 1.42

没用，散了吧

**Comment by youke444** [comment]
微信升级了 7.03     
 
7.0已经作废

**Comment by Mofisto** [comment]
求适配7.0.3

**Comment by veryyoung** [comment]
supported
