### ISSUE TITLE
请添加是否隐藏图标选项

### ISSUE THREAD

**Issue by lin375691011** [veryyoung/WechatLuckyMoney#23]
可能很多同学都有隐藏图标的需求，但是三星系列手机隐藏图标后无法设置“自启动”。这样做的结果就是模块运行一段时间后在手机锁屏状态下会被系统自动杀掉以节省电量和系统资源，表现就是待机时间模块因被系统结束而无法抢到红包。麻烦大神了。

**Comment by veryyoung** [comment]
@lin375691011 杀进程应该和是否有图标没有任何关系吧？

**Comment by aviraxp** [comment]
我看了代码，模块也不用后台吧？

**Comment by lin375691011** [comment]
@veryyoung  设置是否杀应用的这个应用对其他应用默认是熄灭屏幕一段时间后杀掉，如果不想杀掉的话就要进去设置。但是图标隐藏之后在这个应用中就找不到了   所以就没法设置了 所以就杀掉了

**Comment by veryyoung** [comment]
@aviraxp @lin375691011 后台与否模块根本不用设置，和图标也更没关系。

**Comment by lin375691011** [comment]
@veryyoung  可是为啥我的手机上1.0.4可以用  1.0.5熄屏一段时间后就抢不了红包了  然后要进installer点开模块才能接着用。。
