### ISSUE TITLE
微信检测到了插件如何处理

### ISSUE THREAD

**Issue by qq591409016** [veryyoung/WechatLuckyMoney#27]
按照步骤，去除tinker目录权限还是不行，微信照样提示卸载插件并重新登陆，请问大神如何解决？

**Comment by SolSolis** [comment]
同是使用者，推测是你没有开启自己发的红包不抢，这样发私包的时候还自动抢就会被系统识别出使用插件，本人关闭之后就不再提示了。

**Comment by leoleeah** [comment]
我的data目录里没有tinker目录，手机是nexus6P 6.0.1版本，总是提示有插件，要求重新登录，现在把自己发的不抢开启，关闭这个功能后不再提示重新登录

**Comment by veryyoung** [comment]
好的，收到。多谢你们的反馈。

**Comment by 873578156** [comment]
就知道你没睡

**Comment by LuYANGGG** [comment]
反馈一个问题，不知是不是个例：打开免打扰之后就抢不到了。
希望加入的功能：
1.抢完之后自动发送消息，比如谢谢什么的。
2.指定群不抢，指定群延迟。

**Comment by aviraxp** [comment]
打开免打扰之后，微信本身就不会及时接收消息。估计是为了缓解服务器压力。

目前你只能关闭免打扰。

**Comment by veryyoung** [comment]
1.0.6版本自己发的私聊红包不会抢了

**Comment by ycdm** [comment]
@leoleeah 请问找到被封的原因了吗

**Comment by ycdm** [comment]
@veryyoung  有没有可能是识别的包名
