### ISSUE TITLE
1.0.6是只支持6.2.23？

### ISSUE THREAD

**Issue by renyouguo** [veryyoung/WechatLuckyMoney#28]
貌似好多天没效果了，查了下，难道是只支持6.2.23不再支持6.2.22？
看更新日志，还以为是增加新版本支持的意思。

**Comment by veryyoung** [comment]
@renyouguo  我不兼容旧版，只支持最新版。

**Comment by renyouguo** [comment]
@veryyoung 其实我想说的是：如果可以，保持最新版和最近一个历史版本的兼容性，毕竟 wechatui 适配没那么快。
如果坚决只支持最新版，那就把更新日志写得更清楚一些。现在只写“适配”，有歧义啦。

**Comment by veryyoung** [comment]
@renyouguo 这个建议不错。

**Comment by renyouguo** [comment]
@veryyoung 1.0.7 时候还支持6.3.23？

**Comment by renyouguo** [comment]
@aviraxp 谢谢。
很好奇，你怎么会注意到这个已经被关闭的问题的新评论的？

**Comment by aviraxp** [comment]
我 watch了这个项目
