### ISSUE TITLE
微信无法启动

### ISSUE THREAD

**Issue by lirui874125** [veryyoung/WechatLuckyMoney#29]
安卓版本：5.1.1
微信版本：6.3.25
xposed版本：86
使用红包插件后微信可以收到消息，可以抢红包，但是无法打开微信界面，只能后台运行！

**Comment by aviraxp** [comment]
参照https://github.com/veryyoung/WechatLuckyMoney/issues/13

**Comment by ddatsh** [comment]
没有tinker 文件夹，也是闪退

**Comment by ddatsh** [comment]
6.3.25闪退
6.2.23不闪
插件最新版本1.0.7

**Comment by nqs120** [comment]
刚升级了微信，就出现进不去界面，怎么解决？
