### ISSUE TITLE
6.3.25闪退

### ISSUE THREAD

**Issue by freshbird** [veryyoung/WechatLuckyMoney#32]
调试信息显示在Main.java第144行崩溃，错误信息：
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI

我打开微信6.3.25的包查看，并没有看到com.tencent.mm.plugin.luckymoney.ui.LuckyMoneyReceiveUI这个类，是否需要重新调整代码了？(PS:我搜索了整个包所有的class，没找到名为LuckyMoneyReceiveUI的类，请加我QQ4157874交流下啊）

降级到6.3.23解决了

**Comment by veryyoung** [comment]
@freshbird 可能是被热发了。

怎么防热发请参考 https://github.com/veryyoung/WechatLuckyMoney/issues/13

**Comment by aviraxp** [comment]
这个类是有的。在class3.dex里。
