### ISSUE TITLE
抢到自动回复，或者设置个提醒（我现在微信都不开声音和振动！）

### ISSUE THREAD

**Issue by gMan1990** [veryyoung/WechatLuckyMoney#33]
不然群主得踢人了！~

**Comment by gMan1990** [comment]
自动回复比如可以随机中一批中选~

**Comment by gMan1990** [comment]
关闭之后能收到提醒么？不@情况下。
这个版本好像抢不了红包，不知道怎么滴，6.3.23可以的，后来升级了下就貌似嗝屁了
http://dldir1.qq.com/weixin/android/weixin6325android861.apk
@veryyoung

**Comment by aviraxp** [comment]
`Toast.makeText(mContext, "抢到红包", Toast.LENGTH_LONG).show();`
