### ISSUE TITLE
被人抄了

### ISSUE THREAD

**Issue by aviraxp** [veryyoung/WechatLuckyMoney#38]
http://repo.xposed.info/module/gzp.wechatluckmoney

你用的是GPLV3协议，他这个是闭源的

**Comment by veryyoung** [comment]
@aviraxp 有逆向看过代码吗？

**Comment by aviraxp** [comment]
` protected void afterHookedMethod(XC_MethodHook.MethodHookParam paramMethodHookParam)
  {
    if (!c.a()) {}
    do
    {
      return;
      i = XposedHelpers.getIntField(paramMethodHookParam.thisObject, "field_type");
    } while (((i != 436207665) && (i != 469762097)) || (((Integer)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_status")).intValue() == 4) || (((Integer)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_isSend")).intValue() != 0));
    Object localObject1 = (String)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_talker");
    paramMethodHookParam = (String)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_content");
    paramMethodHookParam = main.a(this.b, paramMethodHookParam, "nativeurl");
    Object localObject2 = Uri.parse(paramMethodHookParam);
    int i = Integer.parseInt(((Uri)localObject2).getQueryParameter("msgtype"));
    int j = Integer.parseInt(((Uri)localObject2).getQueryParameter("channelid"));
    localObject2 = ((Uri)localObject2).getQueryParameter("sendid");
    paramMethodHookParam = XposedHelpers.newInstance(XposedHelpers.findClass("com.tencent.mm.plugin.luckymoney.c.ab", this.a.classLoader), new Object[] { Integer.valueOf(i), Integer.valueOf(j), localObject2, paramMethodHookParam, "", "", localObject1, "v1.0" });
    localObject1 = XposedHelpers.callStaticMethod(XposedHelpers.findClass("com.tencent.mm.model.ah", this.a.classLoader), "tv", new Object[0]);
    if (c.b()) {}
    for (i = c.c();; i = 100)
    {
      XposedHelpers.callMethod(localObject1, "a", new Object[] { paramMethodHookParam, Integer.valueOf(i) });
      return;
    }
  }`

跟你

**Comment by aviraxp** [comment]
```
  protected void afterHookedMethod(XC_MethodHook.MethodHookParam paramMethodHookParam)
  {
    if (!c.a()) {}
    do
    {
      return;
      i = XposedHelpers.getIntField(paramMethodHookParam.thisObject, "field_type");
    } while (((i != 436207665) && (i != 469762097)) || (((Integer)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_status")).intValue() == 4) || (((Integer)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_isSend")).intValue() != 0));
    Object localObject1 = (String)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_talker");
    paramMethodHookParam = (String)XposedHelpers.getObjectField(paramMethodHookParam.thisObject, "field_content");
    paramMethodHookParam = main.a(this.b, paramMethodHookParam, "nativeurl");
    Object localObject2 = Uri.parse(paramMethodHookParam);
    int i = Integer.parseInt(((Uri)localObject2).getQueryParameter("msgtype"));
    int j = Integer.parseInt(((Uri)localObject2).getQueryParameter("channelid"));
    localObject2 = ((Uri)localObject2).getQueryParameter("sendid");
    paramMethodHookParam = XposedHelpers.newInstance(XposedHelpers.findClass("com.tencent.mm.plugin.luckymoney.c.ab", this.a.classLoader), new Object[] { Integer.valueOf(i), Integer.valueOf(j), localObject2, paramMethodHookParam, "", "", localObject1, "v1.0" });
    localObject1 = XposedHelpers.callStaticMethod(XposedHelpers.findClass("com.tencent.mm.model.ah", this.a.classLoader), "tv", new Object[0]);
    if (c.b()) {}
    for (i = c.c();; i = 100)
    {
      XposedHelpers.callMethod(localObject1, "a", new Object[] { paramMethodHookParam, Integer.valueOf(i) });
      return;
    }
  }
```

**Comment by veryyoung** [comment]
@aviraxp 好的，多谢。

我去联系他，要求他开源。

**Comment by gMan1990** [comment]
哎，抢不过iPhone，怎么破

**Comment by nany233** [comment]
转发朋友圈功能 怎么实现呢  聊天转发 跟 朋友圈 转发

**Comment by gMan1990** [comment]
@nany233 http://repo.xposed.info/module/com.fkzhang.wechatforwarder

**Comment by nany233** [comment]
@gMan1990 、没有开源啊。

**Comment by gMan1990** [comment]
@nany233 哦，你是问怎么用代码实现，我还以为你只是使用功能。。

**Comment by xhsJ88** [comment]
怎么不能自动抢了
