### ISSUE TITLE
微信无法联网

### ISSUE THREAD

**Issue by wangzhenjiang** [veryyoung/WechatLuckyMoney#39]
今天早上起来，微信无法联网了，禁用红包重启之后，就好了。

机型：sony z2，系统：6.0.1 

：）

**Comment by veryyoung** [comment]
参考 https://github.com/veryyoung/WechatLuckyMoney/issues/13

**Comment by wangzhenjiang** [comment]
昨天还能用呢，是不是抽风？

**Comment by wangzhenjiang** [comment]
厉害，完美解决。顺带还解决了另外一个问题：微信界面进入聊天对话框时，在按系统的返回键，无法退出，点一下，假死，点两下，才能滑动。但无法退出。

**Comment by veryyoung** [comment]
嘿嘿，觉得好就给项目点个 star 哦 @wangzhenjiang

**Comment by xhsJ88** [comment]
Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies 
of this license document, but changing it is not allowed.
