### ISSUE TITLE
如何快速定位到要找的函数？？

### ISSUE THREAD

**Issue by 231599447** [veryyoung/WechatLuckyMoney#41]
目前只能根据反编译后的smali慢慢一点点分析，但是很难找到关键函数。。

不知道作者是否有其他更好的办法可以分析一下？

**Comment by veryyoung** [comment]
诀窍没有，技巧可能有几条吧~

1.  从人类能感知到的地方开始入手。比如通过界面上的字，或者 Toast 开始入手，慢慢往后找。
2.  抓包。抓包之后，搜索对应包的字段，肯定有对应模型和返回结果对应的！~
3.  通过 Log 或者 Toast，可以修改 apk 植入，也可以用 xposed 挂钩子。
