### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by xhsJ88** [veryyoung/WechatLuckyMoney#42]
Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies 
of this license document, but changing it

**Comment by xhsJ88** [comment]
Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies 
of this license document, but changing it

**Comment by veryyoung** [comment]
@xhsJ88 What do you want to do?

**Comment by aviraxp** [comment]
这种都是注册的机器人账号。。。
