### ISSUE TITLE
1.1.0通过Android Studio编译进去不能自动拆包

### ISSUE THREAD

**Issue by iwanglian** [veryyoung/WechatLuckyMoney#44]
使用Xposed Installer上下载来的模块，可以正常抢红包。
但自己用最新代码，用Android Studio打包安装进手机，不能抢红包。

打包安装的步骤有限制吗？

**Comment by aviraxp** [comment]
关掉instant run试试 在2016年11月21日 11:25 ，AlickWang写道： 使用Xposed Installer上下载来的模块，可以正常抢红包。 但自己用最新代码，用Android Studio打包安装进手机，不能抢红包。 打包安装的步骤有限制吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by iwanglian** [comment]
多谢，关掉instant run就可以了

**Comment by ycdm** [comment]
@aviraxp @iwanglian AS 直接装进手机需要重启才生效吗

**Comment by veryyoung** [comment]
@ycdm 必须需要。这可是 Xposed module..
