### ISSUE TITLE
自动转账给某人10块钱是什么鬼啊

### ISSUE THREAD

**Issue by elicec** [veryyoung/WechatLuckyMoney#47]
看见代码里有一段 好像是启动微信的时候，会自动向一个微信账户转账10元？？但是没看见起作用啊？什么鬼啊

**Comment by veryyoung** [comment]
给捐赠使用。不是自动的，点击微信捐赠后自动进入了微信转账界面而已。

**Comment by a8416183** [comment]
6.3.32无法抢红包，怎么回事？
