### ISSUE TITLE
能否在延时时间上再加上随机时间功能？

### ISSUE THREAD

**Issue by fengyie007** [veryyoung/WechatLuckyMoney#48]
比如说设置延时1s，前后100ms内取随机时间？

**Comment by veryyoung** [comment]
@fengyie007 你这种是小众需求。

代码在这儿呢，自己改一个呗。

**Comment by chenweifei** [comment]
需要这样的功能

**Comment by veryyoung** [comment]
@fengyie007 @chenweifei 随机延时的功能没加，很单纯的原因是我不会画范围选择的 ui，如果你们谁能帮忙弄一下就好了。

**Comment by fengyie007** [comment]
只要个数字输入框就好了。 标题 +-随机时间

**Comment by veryyoung** [comment]
@fengyie007 输入框太不优美了，想搞成双向选择的 seekbar，最好还得是 md 的。
