### ISSUE TITLE
大神可否教教我 

### ISSUE THREAD

**Issue by qssq** [veryyoung/WechatLuckyMoney#50]
不知道该怎么弄 求教思路

**Comment by qssq** [comment]
................小气鬼

**Comment by Sheng0** [comment]
这态度谁乐意教你。。。作者有自己的事，教你是情分，不教是本分

**Comment by Jack0001** [comment]
Github怎么也开始涌入小学生了......心疼作者

**Comment by veryyoung** [comment]
@qssq 请先学会如何有效的提问。

建议读一下 <提问的艺术>

**Comment by qssq** [comment]
总喜欢摆出逼格，

**Comment by qssq** [comment]
直接关闭  我说个小气鬼 就变成小气鬼了？
直接关闭 很让人无解的，不清楚我问的什么说一下就好了， 其实不要以为我没有礼貌 彼此彼此。。

我是太急躁了 就问怎么写。可是你们这样喷 就是厚道了么 @小学生 亏你说的出来。
那么再详细的说下吧。
好吧，做出这个东西的起点不需要调试qq吗  就是把qq跑起来 然后 断点调试，
直接逆向源码分析源码 然后hook一些类 然后反复的开关机？打印输出的信息 这样很累的，所以我一直很疑惑。

**Comment by Sheng0** [comment]
你直接这么问也许作者就回你了，之前问的太宽泛了

QingSuiShiQian <notifications@github.com> 於 2016年12月23日 週五 10:04 寫道：

**Comment by qssq** [comment]
@Sheng0 好好好,相互理解下..我错了

**Comment by veryyoung** [comment]
@qssq 请问如果我问你  
>大神可否教教，不知道该怎么弄，求教思路。

你该如何回复？

你到底在问什么问题你应该想清楚。

如果别有问题总问别人，自己思考、Google、debug，探索一番，思路理清楚，然后提出你尝试的过程中遇到的最具体的问题。

**Comment by qssq** [comment]
@veryyoung 好好好，我错了 我可能心情好的时候会发你能具体点吗 可能问的人太多了就慢慢的会对那些描述不详细的人不理不睬了

**Comment by Sheng0** [comment]
@qssq 你问的我也想问，一起学习吧。
我才刚开始搞Android studio，不会的太多了，也只能一点点瞎整

**Comment by Jack0001** [comment]
@qssq 那就请你把态度放端正，如果不想被当成小学生就不要说出这么招黑的话
