### ISSUE TITLE
红包标题过滤

### ISSUE THREAD

**Issue by sakunon** [veryyoung/WechatLuckyMoney#51]
最近发现很多人喜欢在公共群里 发指定人领的红包，能否加入 如果红包名称包含指定关键字/红包名称长度小于设置的长度 不抢功能？

**Comment by Sheng0** [comment]
我在着手弄这个，但是不太会。在向作者请教中，后续作者计划中可能也会添加。

**Comment by veryyoung** [comment]
@Sheng0 @sakunon 代码已经写完了。等下次微信更新了一起发布。

**Comment by sakunon** [comment]
非常感谢~正好学习下怎么写的。

**Comment by veryyoung** [comment]
@sakunon @Sheng0  https://github.com/veryyoung/WechatLuckyMoney/commit/9e9d6b2b827f95c557468d16f0dafc44805a81ee

**Comment by Sheng0** [comment]
@veryyoung 已看到，非常感谢，我自己写的还有问题，抽空学习中。酷安的包似乎有点问题。
