### ISSUE TITLE
经常发生手机锁屏休眠时，迟迟收不到微信消息，这个时候如果有发红包，实际是抢不到的。

### ISSUE THREAD

**Issue by zzyyll2** [veryyoung/WechatLuckyMoney#52]
经常发生手机锁屏休眠时，迟迟收不到微信消息，这个时候如果有发红包，实际是抢不到的。
确认设置里已勾选手机的WIFI常开。
怀疑是休眠下收发消息延迟或减慢，可否设计个定时，半个小时唤醒屏幕一次？

**Comment by veryyoung** [comment]
@zzyyll2 你连微信消息都收不到，当然抢不了红包了。

自动唤醒屏幕不属于本软件的讨论范围。
