### ISSUE TITLE
反检测的一个思路

### ISSUE THREAD

**Issue by ycdm** [veryyoung/WechatLuckyMoney#54]
有一个模块Sudohide

http://repo.xposed.info/module/com.sudocode.sudohide

Source code URL: 
https://github.com/SudoCode755/SudoHide

大概就是hook getPackageInfo 方法 ，把包名信息的返回值清除掉。

让微信找不到你的包名。

**主要是目前不确定什么情况下会检测出来**

**Comment by aviraxp** [comment]
我们也有。

https://github.com/veryyoung/WechatLuckyMoney/blob/master/app/src/main/java/me/veryyoung/wechat/luckymoney/HideModule.java

**Comment by ycdm** [comment]
@aviraxp  也就是说，是服务器后台检测的，现在有随机时间了，被识别的几率是否有下降些呢
