### ISSUE TITLE
插件图标问题

### ISSUE THREAD

**Issue by Alennnnnn** [veryyoung/WechatLuckyMoney#56]
Xposed插件很好用，已捐赠。希望所有插件加个隐藏图标的小功能。我这种强迫症的患者实在有点受不了。望采纳

**Comment by veryyoung** [comment]
@Alennnnnn 自己改吧，很简单。你把这个退回就行了：https://github.com/veryyoung/WechatLuckyMoney/commit/42f958f7e92e1b8c0a3cb1ae3ebb744314e67fe4

**Comment by Alennnnnn** [comment]
这句改了之后直接提示该应用未提供界面-_-
