### ISSUE TITLE
开启免打扰不抢导致正常的也无法自动抢

### ISSUE THREAD

**Issue by jiawei-zheng** [veryyoung/WechatLuckyMoney#58]
微信版本：6.5.3
机型：Nexus 5X

**Comment by veryyoung** [comment]
@jiawei-zheng 免打扰这个功能确实有 bug，适配太麻烦了，准备下掉。

**Comment by jiawei-zheng** [comment]
@veryyoung 我觉得应该不是机型适配的问题，我看瓦力抢红包xposed的代码就是抄你这边的，但是他那边的免打扰功能是正常使用的

**Comment by veryyoung** [comment]
@jiawei-zheng 下个版本免打扰就下了，用新的功能代替
