### ISSUE TITLE
吴大的hidex是否对此模块同样有作用？

### ISSUE THREAD

**Issue by djun** [veryyoung/WechatLuckyMoney#6]
还是需要特地在这个红包模块里面再加入隐藏功能才行？谢谢

**Comment by xfunforx** [comment]
不要乱讲哦。hidex是我写的。

**Comment by veryyoung** [comment]
代码里面加入了隐藏功能

**Comment by xfunforx** [comment]
可能 它们还有 监听 app安装，卸载这种通知。。。最好把这种也处理下了。 不然也可以通过这种方式去了解 手机上安装了哪些app。
好久没看过了。不确定是不是关注这种通知。

**Comment by veryyoung** [comment]
@xfunforx 我去，鹅厂搞这么鸡贼。。。

**Comment by xfunforx** [comment]
很正常的事情了。要习惯。
