### ISSUE TITLE
 compile 'com.crystal:crystalrangeseekbar:1.1.1'

### ISSUE THREAD

**Issue by wxl2578** [veryyoung/WechatLuckyMoney#60]
这个依赖库，Maven 没有啊

**Comment by veryyoung** [comment]
@wxl2578 有。

**Comment by falseen** [comment]
@veryyoung 我也遇到了这个问题，借个楼问一下。
如图：

![image](https://cloud.githubusercontent.com/assets/11572353/22740956/86f4652e-ee4c-11e6-986f-ee3ea868bbc7.png)

是因为网络的原因吗？

**Comment by veryyoung** [comment]
@falseen 是网络原因，挂代理吧。

**Comment by falseen** [comment]
@veryyoung 
我在 gradle.properties 文件中设置了代理，但似乎没有起作用（只对这个依赖不起作用，其他文件都能正常下载）。

**Comment by veryyoung** [comment]
@falseen 那你到网上下个这个 lib，手工丢进去，搞离线模式试试吧

**Comment by falseen** [comment]
@veryyoung 
好的，我试试。
谢谢回复。

**Comment by falseen** [comment]
@veryyoung 
请问下载之后放哪个目录 ？

**Comment by falseen** [comment]
app/build.gradle 中添加如下代码之后，终于编译成功了（需要把下载的crystalrangeseekbar-1.1.1.aar 文件放到app/libs目录）！

```java
repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    provided files('libs/XposedBridgeApi-82.jar')
    compile 'com.android.support:appcompat-v7:23.1.1'
    //compile 'com.crystal:crystalrangeseekbar:1.1.1'
    compile(name:'crystalrangeseekbar-1.1.1', ext:'aar')
}
```

之前一直以为引用的是jar文件，没想到是aar。。。

**Comment by veryyoung** [comment]
@falseen 我这边试是好的，能下下来。
