### ISSUE TITLE
不抢红包

### ISSUE THREAD

**Issue by mjliu** [veryyoung/WechatLuckyMoney#62]
不抢红包啊，重启了也依然不抢。什么情况

**Comment by mjliu** [comment]
难道这个软件需要root手机才好使？

**Comment by wzlu** [comment]
xposed 安装好了？

**Comment by Jack0001** [comment]
首先，这是xposed插件，所以一定要安装xposed框架才能使用，安装xposed框架之前是要root的

**Comment by veryyoung** [comment]
@Jack0001 小学生式的提问不用花时间回答了。
