### ISSUE TITLE
Support wechat 6.5.4

### ISSUE THREAD

**Issue by markzhai** [veryyoung/WechatLuckyMoney#65]

**Comment by WenqiangZhou** [comment]
tkx

**Comment by tanter** [comment]
速度够快啊

**Comment by ares0802** [comment]
timingIdentifier 怎么提前获得？

**Comment by nike022812** [comment]
现在支持6.5.3了嘛

**Comment by xiaojia735** [comment]
怎么下载呀

**Comment by veryyoung** [comment]
@xiaojia735  http://repo.xposed.info/module/me.veryyoung.wechat.luckymoney，麻烦以后别伸手，这么大个链接都看不到。

**Comment by ares0802** [comment]
用getNetworkByModelMethod的a函数把ae参数打包发送一下就可以获得timingIdentifier了，然后在ae的接收消息处截获，按老样子用a函数发送就实现了。这样6.5.4版本要发送两次消息，唯一有点困难的是talker需要保存一下，不然收到的信息跑到别的聊天室去了。

**Comment by smx980723** [comment]
不错

**Comment by smx980723** [comment]
怎么下载

**Comment by 52nome** [comment]
我想问下 veryyoung  你在搜狗就职什么职位?

**Comment by zjacai** [comment]
昨天装了google版的6.5.4，试了，好像不兼容了，大神啥时候放福利

**Comment by xunxuntj** [comment]
不小心升级到654了，哪里有653的apk下载啊

**Comment by veryyoung** [comment]
@52nome 以前在搜狗。现在在滴滴出行，做的事情和 Android 没有任何关系。

**Comment by ivancheng458** [comment]
大神, 做什么都是厉害的！2017年2月7日 上午8:48，veryyoung <notifications@github.com>写道：@52nome 以前在搜狗。现在在滴滴出行，做的事情和 Android 没有任何关系。
