### ISSUE TITLE
快速拆包选项不知道具体作用

### ISSUE THREAD

**Issue by ouyangde** [veryyoung/WechatLuckyMoney#67]
微信版本，6.5.3，华为荣耀6。

打开或者关闭该选项，没什么变化，都是自动就抢了红包。

但是我从代码中看，貌似快速拆包会找个按钮点一下。

我是自己发的红包测试的，不知道有什么影响不。

**Comment by veryyoung** [comment]
@ouyangde 快速拆包就是可以帮助你在关掉自动抢红包的情况下，能省掉红包二次确认的麻烦。
