### ISSUE TITLE
Ur LuckyMoney don't support Wechat new version 6.5.4, pls update and publish it ASAP

### ISSUE THREAD

**Issue by chnto2008** [veryyoung/WechatLuckyMoney#69]
Ur LuckyMoney don't support Wechat new version 6.5.4, pls update and publish it asap. thank you. This app is so useful and funny for get lucky money.

**Comment by EzrealC** [comment]
亲爱的@veryyoung 难道你没有发现微信升级到了6.5.4吗？或许你正在码代码

**Comment by veryyoung** [comment]
@EzrealC 盗版猖獗，先不更新了。看看盗版们有没有能力更新。

**Comment by EzrealC** [comment]
赞成。无论如何在大年30之前释出新版好吗(*˘︶˘*).。.:*♡@veryyoung

**Comment by veryyoung** [comment]
@EzrealC 需要的就用旧版呗。晚上我就回家了，不带电脑。

**Comment by ivancheng458** [comment]
这个跟丁丁有啥区别？为啥要做两个同样功能的呢？
