### ISSUE TITLE
小米手机无法抢红包

### ISSUE THREAD

**Issue by lpx20000** [veryyoung/WechatLuckyMoney#70]
手机破解了，框架装上也激活了，红包插件也好了，但是，有红包的话，插件没反应，即使我再群里自己发，它也没反应，好奇怪

**Comment by 52nome** [comment]
应该是版本不对，如果版本对应的话请重新安装一下微信

**Comment by lpx20000** [comment]
版本是如何对应的？我微信重装了，最新版微信 ，还是没反应 ，不过，如果你点击红包，感觉速度确实会快一点，但是不会自动抢

**Comment by 52nome** [comment]
最新版的插件是可以匹配6.5.4的 如果比6.5.4更高的版本的微信是不能使用，如果重装了之后还不能使用请手机重启以后 ，然后找到微信红包的app点开 看是否开启状态

**Comment by veryyoung** [comment]
@52nome 不适配 6.5.4。。。

麻烦各位看看 README 好吗？

别总问这些问题。

**Comment by 52nome** [comment]
没仔细读完  我看写错了 发出去了就发出去了不好意思
