### ISSUE TITLE
6.5.4提示“请勿使用抢红包辅助软件”怎么破？

### ISSUE THREAD

**Issue by javaboy863** [veryyoung/WechatLuckyMoney#83]
【异常操作警告】请勿使用抢红包辅助软件，并尽快卸载。若再次使用，将在一段时间内无法正常领取红包。

**Comment by veryyoung** [comment]
@javaboy863 https://github.com/veryyoung/WechatLuckyMoney/blob/master/app/src/main/java/me/veryyoung/wechat/luckymoney/HideModule.java 已有规避检测策略。
