### ISSUE TITLE
在哪一个代码处判断成功抢到红包

### ISSUE THREAD

**Issue by czgczg308** [veryyoung/WechatLuckyMoney#90]
楼主，你好。在那一个代码处能判断到成功抢到红包？在哪里能取到用户的id和昵称呢？

**Comment by falseen** [comment]
现在的代码只管发送请求，不管接收。如果你想判断有没有抢到红包的话，对接收到的消息做一个判断就行了。现在的代码是如果检测到接收到的信息是红包的话就调用相应的代码，你可以稍微改一下。至于id和昵称，如果你要的是打开红包之后的id和昵称的话那爱莫能助。如果不是的话，现有的代码已经实现了，直接拿出来用就行。

**Comment by czgczg308** [comment]
谢谢楼主
