### ISSUE TITLE
我的lenovo S660 刷了MIUI7 抢不到红包 。。

### ISSUE THREAD

**Issue by limkaz** [veryyoung/WechatLuckyMoney#98]

**Comment by metoox** [comment]
换一个模块，好多种

**Comment by limkaz** [comment]
可以给网址吗？

**Comment by veryyoung** [comment]
@limkaz 没有 miui 7，没法测试。这个得希望你们能提供一点力量了。

**Comment by theopengroup** [comment]
力气不够

**Comment by limkaz** [comment]
提供什么力量=。=

**Comment by veryyoung** [comment]
@limkaz 自己用 miui 手机 debug 试试。

**Comment by walaoaaa1234** [comment]
``
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mm.plugin.luckymoney.c.ae
``
我的oppo也不能抢。。。6.5.4, 6.5.6, 都不能用

**Comment by limkaz** [comment]
Debug 怎样？

**Comment by lelilin** [comment]
看了你开放的微信红包Code,请教个xposed红包问题
 callMethod(requestCaller, "a", luckyMoneyRequest, getDelayTime());  --------为抢红包函数请求.
 若查询红包明细请求,call和hook哪个函数呢?

**Comment by veryyoung** [comment]
我没法挨个设备测，我只能保证我在 Nexus 上跑着好好的。

都已经是开源项目了，你们自己拿着 debug 下，完事给代码做个修补，难道不是更好吗？
